### ISSUE TITLE
困难本添加自定义描述

### ISSUE THREAD

**Issue by steamqaqwq** [sanmusen214/BAAH#101]
多个困难本刷久容易忘记原先刷的是啥，添加描述方便定位修改。如图18-3可以添加阿露描述，UI可以改进一下。
![image](https://github.com/user-attachments/assets/075982ea-f28d-40fe-bed3-c082f87a1d27)

**Comment by ly5519** [comment]
日服已经针对物品掉落刷取做了优化，推荐以最终版本为模板
![image](https://github.com/user-attachments/assets/21354637-060e-46d8-9c5f-e042f7505f6d)
还可以保存刷取本次刷取的内容，下一次直接选择刷取

**Comment by sanmusen214** [comment]
81a1c7d 在任务标题下方加了个自定义注释框，等国际服实装一键扫荡后会适配一键扫荡功能

**Comment by sanmusen214** [comment]
Closed with https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.6.2
