### ISSUE TITLE
[Want] 单元测试模块

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#103]
**Is your feature request related to a problem? Please describe. / 该功能请求能解决你认为的何种困难？**
这是目前整个项目的结构（除去了用户配置文件夹BAAH_CONFIGS）
![image](https://github.com/user-attachments/assets/8d5762a3-b464-43f5-82e2-d90351d66e24)

其中 Python 代码有 6,862 行。这个代码量对于一个中等规模的项目来说是相当大的，值得考虑编写单元测试来确保代码的质量和稳定性。

**Describe the solution you'd like / 你对于实现该功能有何种建议**
作为单元测试并不影响整个项目运行逻辑，不阻塞其他功能，我可以慢慢写🤭，当然如果森哥觉得项目目前迭代很快，增加单元测试只会拖累项目进度，可以把测试的问题往后靠一靠也不迟

**Additional context / 补充信息**
对于写给单元测试写写用例也是一个很好的熟悉项目的办法

**Comment by sanmusen214** [comment]
对哪些模块进行单元测试呢，目前一个问题是大部分主要功能需要游戏运行时测试

**Comment by ly5519** [comment]
可以使用mock模拟环境，也可以拆细一点，把代码逻辑提取出来，并不是每一个method都调用了安卓adb，也可以使用集成测试，直接让测试单元跑在有adb的模拟器下也不是不可以，当然我对这方面认知比较少，在之前的工作里也只写了少量的测试用例，mock用的也不是很熟练

**Comment by sanmusen214** [comment]
好滴捏，项目根目录新建test文件夹，不影响主程序就行

**Comment by ly5519** [comment]
please help for this
![image](https://github.com/user-attachments/assets/4ae705db-ed6f-4067-b035-67251b9efcd6)
what the mean?

**Comment by sanmusen214** [comment]
> what the mean?

用于共享软件的设置的一个config实例。Config会解析BAAH_CONFIGS下的任务配置和DATA/CONFIGS里的软件配置，由于不同tab标签页使用的Config实例是隔离的，所以额外建了一个shared_softwareconfig专门用来共享shared_softwareconfig.softwareconfigdict里的内容

**Comment by ly5519** [comment]
@sanmusen214  look this PR

**Comment by ly5519** [comment]
进展困难最近不打算写了有别的事情要做先关了

**Comment by ly5519** [comment]
不打算从头开始写test了，想委托森哥，觉得哪部分代码是写的比较好的，短期内不会频繁变动的，指哪打哪

**Comment by sanmusen214** [comment]
> 不打算从头开始写test了，想委托森哥，觉得哪部分代码是写的比较好的，短期内不会频繁变动的，指哪打哪

软件发布测试不太好做，一个是主要功能太依赖模拟器环境了，一个是Task内部只划分了pre, run, post三个比较基础的阶段。
比较好测的估计只有ocr和图片匹配
