### ISSUE TITLE
日服活动推图失败

### ISSUE THREAD

**Issue by huihuiotc** [sanmusen214/BAAH#106]
![屏幕截图 2024-08-21 214011](https://github.com/user-attachments/assets/158c1a4f-d4e2-4dcd-aab5-55fa94564da1)

**Comment by sanmusen214** [comment]
队伍选择页面标题变了，过会修

**Comment by sanmusen214** [comment]
closed with https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.6.3
