### ISSUE TITLE
[Want] 添加 docker 支持

### ISSUE THREAD

**Issue by lonzzi** [sanmusen214/BAAH#108]
**Is your feature request related to a problem? Please describe. / 该功能请求能解决你认为的何种困难？**
[ Ex. I'm always frustrated when ... ]

使用 docker 方便 server 部署

**Describe the solution you'd like / 你对于实现该功能有何种建议**
[ A clear and concise description of what you think about the solution. ]

使用 docker 部署需要 web 一直运行，并且需要添加定时任务、web 启动( #73 ) 来满足自定义需求。

**Additional context / 补充信息**
[ Add any other context or screenshots about the feature request here. ]

**Comment by sanmusen214** [comment]
等我这几天搞完毕设。你有空的话也可以琢磨琢磨

**Comment by sanmusen214** [comment]
此功能安排在 #73 之后
