### ISSUE TITLE
[Help Want]实体机左右ui留有异形屏适配导致的空白

### ISSUE THREAD

**Issue by heixiaoou** [sanmusen214/BAAH#110]
Before you raise this issue, plz make sure it is not duplicated / 在你提出该issue之前，请确保它以前从未被提及过.

**Describe the bug / 描述bug**
[ What you want to do and what the script did / 你想要脚本做什么，而它做了什么出乎意料的事 ]
我是用的实体安卓设备，用usb连接并启用了开发者模式，并使用adb调整了分辨率为720x1280，设置完成后卡在此界面并重复此句话
当前运行的app是：com.YostarJP.BlueArchive/com.yostarjp.bluearchive.MxUnityPlayerActivity
**Screenshots / 截图**
[ Plz attach any screenshots of emulator or logs / 请提供相关日志以及模拟器的截图 ]
![image](https://github.com/user-attachments/assets/2a7c8f27-f549-4123-b020-a2bf068f72ae)
![image](https://github.com/user-attachments/assets/dce89a87-c552-45a5-b7c7-4b56e6e4cd42)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: JP
 - BAAH version / 你的BAAH版本号: 1.6.4

**Comment by sanmusen214** [comment]
实体机尽管修改了分辨率和dpi，屏幕左右两侧UI还是会留有多余的空白区域，疑似是系统对挖孔/刘海全面屏的防遮挡设置，目前没找到方法去除

**Comment by sanmusen214** [comment]
Closed due to this is not highly related to BAAH itself, welcome any solution though
由于和BAAH本体关联不大，此Issue关闭，如果有解决方案的话欢迎告知

**Comment by sanmusen214** [comment]
> 目前没找到方法去除

如果手机设置提供了如 隐藏刘海 等功能，开启后一般就可以去除这种UI空白距离了
