### ISSUE TITLE
[BUG] 竞技场商店切换失败

### ISSUE THREAD

**Issue by steamqaqwq** [sanmusen214/BAAH#119]
Before you raise this issue, plz make sure it is not duplicated / 在你提出该issue之前，请确保它以前从未被提及过.

**Describe the bug / 描述bug**
[ What you want to do and what the script did / 你想要脚本做什么，而它做了什么出乎意料的事 ]
国际服更新后，进不去竞技场商店

**Screenshots / 截图**
[ Plz attach any screenshots of emulator or logs / 请提供相关日志以及模拟器的截图 ]
![image](https://github.com/user-attachments/assets/098d6a15-de30-43ca-9b98-04a758b7e274)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: 国际服
 - BAAH version / 你的BAAH版本号: 1.6.8

**Comment by sanmusen214** [comment]
下个版本修复

**Comment by sanmusen214** [comment]
closed with 1.6.9 #120
