### ISSUE TITLE
学园交流和悬赏通缉有点问题

### ISSUE THREAD

**Issue by Chuangludeng** [sanmusen214/BAAH#12]
学园交流和悬赏通缉有点问题..我配置的时每个区域刷5次,但是脚本执行了第一个5次后,就提示没有票了,跳过了后两个.想了一下可能是把10识别成了0,我开了大小月卡有15张票

**Comment by sanmusen214** [comment]
已于 df3f911 修复，如还有问题请再次反馈，谢谢

**Comment by sanmusen214** [comment]
新版本还在测试中，请到群内下载测试版

**Comment by sanmusen214** [comment]
版本已发布，issue关闭
