### ISSUE TITLE
[Want] 可选择运行结束后只关闭BAAH

### ISSUE THREAD

**Issue by ERROR0cai** [sanmusen214/BAAH#121]
**Is your feature request related to a problem? Please describe. / 该功能请求能解决你认为的何种困难？**
[ Ex. I'm always frustrated when ... ]

我希望可以在定时触发后等待我的手操，但是又不希望BAAH一直等待我回车去关闭

**Describe the solution you'd like / 你对于实现该功能有何种建议**
[ A clear and concise description of what you think about the solution. ]

或许可以把关闭BAAH的代码和关闭模拟器对应两个勾选框（？）（这样的话甚至可以让用户自由自定义运行结束后关闭BAAH或关闭模拟器了qwq）

**Additional context / 补充信息**
[ Add any other context or screenshots about the feature request here. ]

也不是很着急的啦~

**Comment by sanmusen214** [comment]
于1.7.0 实现 #124  ，感谢建议

**Comment by ERROR0cai** [comment]
> 于1.7.0 实现 #124 ，感谢建议

感谢作者大大
