### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GenLiya** [sanmusen214/BAAH#123]
Before you raise this issue, plz make sure it is not duplicated / 在你提出该issue之前，请确保它以前从未被提及过.

**Describe the bug / 描述bug**
[ What you want to do and what the script did / 你想要脚本做什么，而它做了什么出乎意料的事 ]
在学院交流会和活动关卡的刷取中，它出现了无法识别模板图像的问题

**Screenshots / 截图**
[ Plz attach any screenshots of emulator or logs / 请提供相关日志以及模拟器的截图 ]
使用语言/Use language:  zh_CN
2024-11-03 01:44:02.6709089 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
1.6.9 - 44:02 - INFO : 当前运行目录: E:\script\baah\BAAH1.6.9
1.6.9 - 44:02 - INFO : BAAH_CONFIGS可用的配置文件: example.json
1.6.9 - 44:02 - INFO : 读取指定的配置文件: example.json
+======================================BAAH====================================== +
||                                 Version: 1.6.9                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                              QQ group: 441069156                               ||
||                                                                                ||
+================================================================================+
1.6.9 - 44:03 - INFO : 读取的配置文件: example.json
1.6.9 - 44:03 - INFO : 模拟器:E:/MuMu Player 12/shell/MuMuMultiPlayer.exe
1.6.9 - 44:03 - INFO : 端口:16480
1.6.9 - 44:03 - INFO : 区服:CN
1.6.9 - 44:03 - INFO : 启动模拟器
1.6.9 - 44:03 - INFO : 模拟器pid: 23172
1.6.9 - 44:08 - INFO : MuMuMultiPlayer.exe | 23172 | Console | 1 | 65,960 | K
1.6.9 - 44:09 - INFO : 删除e2419474.png
1.6.9 - 44:12 - INFO : 截图文件大小为918KB
1.6.9 - 44:12 - INFO : adb与模拟器连接正常
1.6.9 - 44:12 - INFO : 图片分辨率为1280*720
1.6.9 - 44:12 - INFO : DPI: Physical density: 240

1.6.9 - 44:12 - INFO : adb连接成功
1.6.9 - 44:12 - INFO : 跳过启动加速器
1.6.9 - 44:12 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 44:12 - INFO : 检测到游戏已经在运行
1.6.9 - 44:12 - INFO : 运行任务
1.6.9 - 44:12 - INFO : 判断任务EnterGame是否可以执行
1.6.9 - 44:17 - WARN : run_until exceeded max times
1.6.9 - 44:17 - WARN : 任务EnterGame执行前条件不成立或超时，跳过此任务
1.6.9 - 44:17 - INFO : 判断任务InContest是否可以执行
1.6.9 - 44:17 - INFO : 尝试返回主页
1.6.9 - 44:17 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 44:18 - INFO : 返回主页成功
1.6.9 - 44:18 - INFO : 执行任务InContest
1.6.9 - 44:29 - ERROR : 识别竞技场信息错误: invalid literal for int() with base 10: ''
1.6.9 - 44:33 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_EDIT.png
1.6.9 - 44:42 - INFO : 设置的该次执行战术大赛不收集奖励, 直接返回主页
1.6.9 - 44:42 - INFO : 尝试返回主页
1.6.9 - 44:42 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 44:47 - INFO : 返回主页成功
1.6.9 - 44:47 - INFO : 判断任务InContest执行结果是否可控
1.6.9 - 44:47 - INFO : 任务InContest执行结束
1.6.9 - 44:47 - INFO : 判断任务InContest是否可以执行
1.6.9 - 44:47 - INFO : 尝试返回主页
1.6.9 - 44:47 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 44:48 - INFO : 返回主页成功
1.6.9 - 44:48 - INFO : 执行任务InContest
1.6.9 - 45:00 - ERROR : 识别竞技场信息错误: invalid literal for int() with base 10: ''
1.6.9 - 45:04 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_EDIT.png
1.6.9 - 45:51 - INFO : 尝试返回主页
1.6.9 - 45:51 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 45:55 - INFO : 返回主页成功
1.6.9 - 45:55 - INFO : 判断任务InContest执行结果是否可控
1.6.9 - 45:56 - INFO : 任务InContest执行结束
1.6.9 - 45:56 - INFO : 判断任务CollectDailyRewards是否可以执行
1.6.9 - 45:56 - INFO : 执行任务CollectDailyRewards
1.6.9 - 46:05 - INFO : 尝试返回主页
1.6.9 - 46:05 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 46:10 - INFO : 返回主页成功
1.6.9 - 46:10 - INFO : 判断任务CollectDailyRewards执行结果是否可控
1.6.9 - 46:10 - INFO : 任务CollectDailyRewards执行结束
1.6.9 - 46:10 - INFO : 判断任务CollectMails是否可以执行
1.6.9 - 46:11 - INFO : 执行任务CollectMails
1.6.9 - 46:28 - WARN : run_until exceeded max times
1.6.9 - 46:28 - INFO : 尝试返回主页
1.6.9 - 46:28 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 46:33 - INFO : 返回主页成功
1.6.9 - 46:33 - INFO : 判断任务CollectMails执行结果是否可控
1.6.9 - 46:33 - INFO : 任务CollectMails执行结束
1.6.9 - 46:33 - INFO : 判断任务InEvent是否可以执行
1.6.9 - 46:34 - INFO : 执行任务InEvent
1.6.9 - 46:41 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 46:41 - INFO : 当前运行的app的前台activity是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 46:44 - INFO : QUEST按钮匹配结果: True
1.6.9 - 46:44 - INFO : 识别活动时间: ['[:2024.10.24 14:00 ~ 2024.11.07 09:59', 0.94776213]
1.6.9 - 46:44 - INFO : 活动开放中
1.6.9 - 46:44 - INFO : 成功进入Event页面
1.6.9 - 46:44 - INFO : 判断任务EventStory是否可以执行
1.6.9 - 46:45 - INFO : 执行任务EventStory
1.6.9 - 46:49 - INFO : ocr结果：[]
1.6.9 - 46:49 - WARN : 无法获取最大关卡数，结束
1.6.9 - 46:49 - INFO : 判断任务EventStory执行结果是否可控
1.6.9 - 46:50 - INFO : 任务EventStory执行结束
1.6.9 - 46:51 - INFO : 检查活动关卡是否推完
1.6.9 - 46:55 - INFO : ocr结果: [['12', 0.99973875]]
1.6.9 - 46:55 - INFO : 最大关卡: 12，开始检测是否需要推图
1.6.9 - 46:55 - INFO : 判断任务EventQuest是否可以执行
1.6.9 - 46:55 - INFO : 执行任务EventQuest
1.6.9 - 47:04 - INFO : 尝试跳转到第12个level
1.6.9 - 47:23 - INFO : 关闭任务咨询弹窗
1.6.9 - 47:25 - INFO : 不尝试领取奖励
1.6.9 - 47:25 - INFO : 判断任务EventQuest执行结果是否可控
1.6.9 - 47:26 - INFO : 任务EventQuest执行结束
1.6.9 - 47:26 - INFO : 判断任务EventQuest是否可以执行
1.6.9 - 47:26 - INFO : 执行任务EventQuest
1.6.9 - 47:35 - INFO : 尝试跳转到第12个level
1.6.9 - 47:53 - INFO : 开始扫荡
1.6.9 - 47:53 - INFO : 判断任务RaidQuest是否可以执行
1.6.9 - 47:54 - INFO : 执行任务RaidQuest
1.6.9 - 48:02 - WARN : 扫荡（快速战斗）按钮匹配失败，请检查配置文件中的服务器语言，以及是否有反和谐
1.6.9 - 48:03 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:04 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:05 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:06 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:07 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:08 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:09 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:10 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:11 - WARN : 无法匹配模板图像: ./DATA/assets_cn\BUTTON\BUTTON_CFIGHT_START.png
1.6.9 - 48:12 - WARN : run_until exceeded max times
1.6.9 - 48:12 - INFO : 点击弹窗内的确认
1.6.9 - 48:13 - INFO : 判断任务RaidQuest执行结果是否可控
1.6.9 - 48:13 - INFO : 任务RaidQuest执行结束
1.6.9 - 48:13 - INFO : 关闭任务咨询弹窗
1.6.9 - 48:16 - INFO : 尝试领取右下角点数奖励和左下角任务奖励
1.6.9 - 48:20 - INFO : 检测到活动任务页面，尝试领取任务奖励
1.6.9 - 48:29 - INFO : 判断任务EventQuest执行结果是否可控
1.6.9 - 48:29 - INFO : 任务EventQuest执行结束
1.6.9 - 48:29 - INFO : 判断任务InEvent执行结果是否可控
1.6.9 - 48:30 - INFO : 尝试返回主页
1.6.9 - 48:30 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 48:34 - INFO : 返回主页成功
1.6.9 - 48:34 - INFO : 任务InEvent执行结束
1.6.9 - 48:34 - INFO : 判断任务CollectDailyRewards是否可以执行
1.6.9 - 48:35 - INFO : 执行任务CollectDailyRewards
1.6.9 - 48:38 - INFO : 尝试返回主页
1.6.9 - 48:38 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 48:43 - INFO : 返回主页成功
1.6.9 - 48:43 - INFO : 判断任务CollectDailyRewards执行结果是否可控
1.6.9 - 48:43 - INFO : 任务CollectDailyRewards执行结束
1.6.9 - 48:43 - INFO : 判断任务PostAllTask是否可以执行
1.6.9 - 48:44 - INFO : 尝试返回主页
1.6.9 - 48:44 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 48:45 - INFO : 返回主页成功
1.6.9 - 48:45 - INFO : 执行任务PostAllTask
1.6.9 - 48:45 - INFO : 判断任务PostAllTask执行结果是否可控
1.6.9 - 48:45 - INFO : 尝试返回主页
1.6.9 - 48:45 - INFO : 当前运行的app是：com.RoamingStar.BlueArchive/com.yostar.sdk.bridge.YoStarUnityPlayerActivity
1.6.9 - 48:46 - INFO : 返回主页成功
1.6.9 - 48:46 - INFO : 任务PostAllTask执行结束
1.6.9 - 48:46 - INFO : 所有任务结束
1.6.9 - 48:46 - INFO : 跳过关闭模拟器
1.6.9 - 48:46 - INFO : 尝试发送通知
1.6.9 - 48:46 - INFO : 通知发送结束
+======================================BAAH====================================== +
||                                 Version: 1.6.9                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                              QQ group: 441069156                               ||
||                                                                                ||
+================================================================================+

程序运行结束，如有问题请加群(441069156)反馈，在Github上检查下是否有版本更新
https://github.com/sanmusen214/BAAH
1.6.9 - 48:46 - INFO : 读取的配置文件: example.json
1.6.9 - 48:46 - INFO : 模拟器:E:/MuMu Player 12/shell/MuMuMultiPlayer.exe
1.6.9 - 48:46 - INFO : 端口:16480
1.6.9 - 48:46 - INFO : 区服:CN
GUI_BAAH_TASK_END
Press Enter to exit/回车退出, [dict_keys([])]:
反和谐我已经检查过了我的游戏界面显示为桃信，在配置中未勾选关于反和谐的选项
**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: [e.g. Global]国服官服
 - BAAH version / 你的BAAH版本号: [e.g. 1.5.4]1.6.9

**Comment by sanmusen214** [comment]
扫荡页面显示的是“开始快速战斗”还是“开始扫荡”，如果是开始扫荡的话需要勾选已和谐

**Comment by sanmusen214** [comment]
未能复现，使用原版国服官服，手机显示“桃信”，扫荡按钮显示“开始快速战斗”，可以正常扫荡主线关卡。

夏莱情人节活动暂不支持。
