### ISSUE TITLE
[Want]添加消息推送支持Telegram Bot

### ISSUE THREAD

**Issue by rote66** [sanmusen214/BAAH#142]
**Is your feature request related to a problem? Please describe. / 该功能请求能解决你认为的何种困难？**
[ Ex. I'm always frustrated when ... ]

TG BOT应该是除了serverchan和pushplus之外用的比较多的一个推送方案了。

**Describe the solution you'd like / 你对于实现该功能有何种建议**
[ A clear and concise description of what you think about the solution. ]

TG相比那两个只需要token的多了一个chatid。在不改变现有HTTP Sender的和网页gui的逻辑上，就只能手动改url了，就像这样：rote66/BAAH@f0a3a3db328390be777b8d4f2c13164c03d0c901
要不要为了多的这个参数加个框来填写还是保持这种在url中自行添加参数。

**Additional context / 补充信息**
[ Add any other context or screenshots about the feature request here. ]

**Comment by sanmusen214** [comment]
想了下，另外两种方案没有chatid，这样来看直接把放url里就行了

**Comment by rote66** [comment]
> 想了下，另外两种方案没有chatid，这样来看直接把放url里就行了

ok，那我直接pr过来
