### ISSUE TITLE
日服二号咖啡厅，弹框阻拦滑动视角

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#18]
1. 切换到二号咖啡厅中间会弹出本次到来的学生，此时进行的是视角调整的操作。
2. 在咖啡厅先进行学生邀请卷的使用再收集好感是可行，可以节约不少时间摸头移动视角事件

version：Rekeases 1.1.12

**Comment by sanmusen214** [comment]
日服的话在模拟器里把咖啡厅视角手动拉到最高，然后在配置文件里把 进入咖啡厅时视野最高 勾选上

**Comment by ly5519** [comment]
![M5N I{NI$5_ ~Y} 5 {NW3Q](https://github.com/sanmusen214/BAAH/assets/77131638/6223eb63-110a-4d8e-80f2-116e9528fa12)
按照操作今天的自动脚本不会移动视角，是需要手动对准到中间吗

还有就是三次摸头循环，邀请，在进行三次摸头循环
改成邀请之后三次摸头循环有无啥雷点

**Comment by sanmusen214** [comment]
需要把画面（主要是地板）挪到中间
邀请时可能会邀同名的学生（比如体操服优香和优香），直接换下来的话摸头的时候就会少摸一个
