### ISSUE TITLE
自动推图bug

### ISSUE THREAD

**Issue by TheLaulee** [sanmusen214/BAAH#21]
![TF%K4QQ4 ZNPU%S)@Y0ML18](https://github.com/sanmusen214/BAAH/assets/61400239/ff63db18-f2d0-40a9-9c94-1e51dd1872a8)
![0Q(GB`RU`KVGESTW57HJ}GV](https://github.com/sanmusen214/BAAH/assets/61400239/ff0bd77d-7e03-4445-9273-269a8efda3fa)

**Comment by TheLaulee** [comment]
这张图是hard13-2

**Comment by sanmusen214** [comment]
看了下应该是爬攻略的时候出的问题

**Comment by sanmusen214** [comment]
在推图数据1.2.9.zip里修复了
