### ISSUE TITLE
24-4普通，手工配队无法开始，彩虹队超时ERR

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#25]
21-Feb-24 01:19:32 - WARNING - run_until exceeded max times
21-Feb-24 01:19:32 - ERROR - 返回主页失败
Traceback (most recent call last):
  File "C:\Users\liu55\PycharmProjects\BAAH\main.py", line 54, in <module>
    BAAH_main()
  File "C:\Users\liu55\PycharmProjects\BAAH\BAAH.py", line 156, in BAAH_main
    my_AllTask.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\myAllTask.py", line 70, in run
    task.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\InQuest.py", line 52, in on_run
    PushQuest("normal", push_normal_ind, level_ind=config.userconfigdict["PUSH_NORMAL_QUEST_LEVEL"]-1).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\PushQuest.py", line 156, in on_run
    GridQuest(grider=grider, backtopic=lambda: match(page_pic(PageName.PAGE_QUEST_SEL)), require_type=require_types[self.require_type_ind]).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 61, in run
    raise Exception("任务{}执行后条件不成立或超时，且无法正确返回主页，程序退出".format(self.name))
Exception: 任务GridQuest执行后条件不成立或超时，且无法正确返回主页，程序退出

**Comment by ly5519** [comment]
21-Feb-24 01:14:53 - WARNING - 错误的扫荡类型
21-Feb-24 01:14:53 - INFO - 读取的config文件: push.json
21-Feb-24 01:14:53 - INFO - 模拟器:
21-Feb-24 01:14:53 - INFO - 端口:16384
21-Feb-24 01:14:53 - INFO - 区服:JP
21-Feb-24 01:14:53 - INFO - 未配置模拟器路径，跳过启动模拟器
21-Feb-24 01:14:54 - INFO - 删除ca51ec59.png
21-Feb-24 01:14:56 - INFO - 截图文件大小为596KB
21-Feb-24 01:14:56 - INFO - adb与模拟器连接正常
21-Feb-24 01:14:56 - INFO - 图片分辨率为1280*720
21-Feb-24 01:14:56 - INFO - adb连接成功
21-Feb-24 01:14:56 - INFO - 当前运行的app为：  mCurrentFocus=Window{8d8a1c7 u0 com.YostarJP.BlueArchive/com.yostarjp.bluearchive.MxUnityPlayerActivity}
21-Feb-24 01:14:56 - INFO - 检测到游戏已经在运行
21-Feb-24 01:14:56 - INFO - 运行任务
21-Feb-24 01:14:56 - INFO - 判断任务EnterGame是否可以执行
21-Feb-24 01:14:57 - INFO - 尝试返回主页
21-Feb-24 01:15:02 - INFO - 返回主页成功
21-Feb-24 01:15:06 - WARNING - run_until exceeded max times
21-Feb-24 01:15:06 - WARNING - 任务EnterGame执行前条件不成立或超时，跳过此任务
21-Feb-24 01:15:06 - INFO - 判断任务InQuest是否可以执行
21-Feb-24 01:15:07 - INFO - 执行任务InQuest
21-Feb-24 01:15:14 - INFO - 设置了推普通图任务，开始推图
21-Feb-24 01:15:14 - INFO - 判断任务PushQuest是否可以执行
21-Feb-24 01:15:15 - INFO - 执行任务PushQuest
21-Feb-24 01:15:15 - INFO - switch to normal quest
21-Feb-24 01:15:15 - INFO - 尝试跳转至页面 24
21-Feb-24 01:15:21 - INFO - 尝试翻到关卡 4
21-Feb-24 01:15:24 - INFO - 分割后的关卡序号：['24', '4']
21-Feb-24 01:15:24 - INFO - 格子关卡：24-4，开始推图
21-Feb-24 01:15:24 - INFO - 识别到S标签，判断为走格子战斗
21-Feb-24 01:15:27 - WARNING - Cannot find the target pattern ./DATA/assets_jp/BUTTON/BUTTON_TASK_START.png when try to click
21-Feb-24 01:15:29 - INFO - 判断任务GridQuest是否可以执行
21-Feb-24 01:15:31 - INFO - 执行任务GridQuest
21-Feb-24 01:15:31 - INFO - 成功读取关卡文件24-4.json，开始执行
21-Feb-24 01:15:31 - INFO - 使用上次的队伍配置: 
21-Feb-24 01:15:32 - INFO - 配置队伍A
21-Feb-24 01:15:33 - INFO - 点击出击
21-Feb-24 01:15:37 - INFO - 配置队伍B
21-Feb-24 01:15:39 - INFO - 点击出击
21-Feb-24 01:15:45 - INFO - 开始战斗！
21-Feb-24 01:15:49 - INFO - ocr结果1
21-Feb-24 01:15:49 - INFO - 当前聚焦队伍A
21-Feb-24 01:15:49 - INFO - 执行step:0 action:0 队伍A->move right
21-Feb-24 01:15:51 - INFO - 点击[734, 504]
21-Feb-24 01:15:52 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:15:52 - INFO - 尝试呼出弹窗
21-Feb-24 01:15:57 - INFO - 尝试清空弹窗
21-Feb-24 01:16:00 - INFO - ocr结果2
21-Feb-24 01:16:00 - INFO - 当前聚焦队伍B
21-Feb-24 01:16:00 - INFO - 执行step:0 action:1 队伍B->move right
21-Feb-24 01:16:01 - INFO - 点击[694, 277]
21-Feb-24 01:16:03 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:16:03 - INFO - 尝试呼出弹窗
21-Feb-24 01:16:03 - INFO - 尝试清空弹窗
21-Feb-24 01:16:05 - INFO - PHASE结束
21-Feb-24 01:16:08 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:16:08 - INFO - 尝试呼出弹窗
21-Feb-24 01:16:19 - INFO - 尝试清空弹窗
21-Feb-24 01:16:22 - INFO - ocr结果1
21-Feb-24 01:16:22 - INFO - 当前聚焦队伍A
21-Feb-24 01:16:22 - INFO - 执行step:1 action:0 队伍A->move right-down
21-Feb-24 01:16:23 - INFO - 点击[797, 510]
21-Feb-24 01:16:24 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:16:25 - INFO - 尝试呼出弹窗
21-Feb-24 01:16:27 - INFO - 尝试清空弹窗
21-Feb-24 01:16:30 - INFO - ocr结果1
21-Feb-24 01:16:31 - INFO - ocr结果2
21-Feb-24 01:16:31 - INFO - 当前聚焦队伍B
21-Feb-24 01:16:31 - INFO - 执行step:1 action:1 队伍B->move right
21-Feb-24 01:16:33 - INFO - 点击[776, 282]
21-Feb-24 01:16:34 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:16:34 - INFO - 尝试呼出弹窗
21-Feb-24 01:16:37 - INFO - 尝试清空弹窗
21-Feb-24 01:16:39 - INFO - PHASE结束
21-Feb-24 01:16:43 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:16:44 - INFO - 尝试呼出弹窗
21-Feb-24 01:16:55 - INFO - 尝试清空弹窗
21-Feb-24 01:16:57 - INFO - ocr结果1
21-Feb-24 01:16:57 - INFO - 当前聚焦队伍A
21-Feb-24 01:16:57 - INFO - 执行step:2 action:0 队伍A->move left-up
21-Feb-24 01:16:59 - INFO - 点击[649, 422]
21-Feb-24 01:17:00 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:01 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:03 - INFO - 尝试清空弹窗
21-Feb-24 01:17:06 - INFO - ocr结果1
21-Feb-24 01:17:07 - INFO - ocr结果2
21-Feb-24 01:17:07 - INFO - 当前聚焦队伍B
21-Feb-24 01:17:07 - INFO - 执行step:2 action:1 队伍B->move right-down
21-Feb-24 01:17:09 - INFO - 点击[706, 349]
21-Feb-24 01:17:10 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:10 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:15 - INFO - 尝试清空弹窗
21-Feb-24 01:17:17 - INFO - PHASE结束
21-Feb-24 01:17:21 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:22 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:26 - INFO - 尝试清空弹窗
21-Feb-24 01:17:29 - INFO - ocr结果1
21-Feb-24 01:17:29 - INFO - 当前聚焦队伍A
21-Feb-24 01:17:29 - INFO - 执行step:3 action:0 队伍A->move right-up
21-Feb-24 01:17:31 - INFO - 点击[593, 388]
21-Feb-24 01:17:32 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:32 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:34 - INFO - 尝试清空弹窗
21-Feb-24 01:17:37 - INFO - ocr结果1
21-Feb-24 01:17:38 - INFO - ocr结果2
21-Feb-24 01:17:38 - INFO - 当前聚焦队伍B
21-Feb-24 01:17:38 - INFO - 执行step:3 action:1 队伍B->move right
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
21-Feb-24 01:17:40 - INFO - 三角识别失败，尝试使用砖块识别
输入的图片全黑，没有有效像素点
21-Feb-24 01:17:40 - INFO - 点击[639, 295]
21-Feb-24 01:17:41 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:42 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:44 - INFO - 尝试清空弹窗
21-Feb-24 01:17:46 - INFO - PHASE结束
21-Feb-24 01:17:51 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:17:51 - INFO - 尝试呼出弹窗
21-Feb-24 01:17:56 - INFO - 尝试清空弹窗
21-Feb-24 01:17:58 - INFO - ocr结果1
21-Feb-24 01:17:58 - INFO - 当前聚焦队伍A
21-Feb-24 01:17:58 - INFO - 执行step:4 action:0 队伍A->portal left-down
21-Feb-24 01:18:00 - INFO - 点击[452, 537]
21-Feb-24 01:18:03 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:18:04 - INFO - 尝试呼出弹窗
21-Feb-24 01:18:06 - INFO - 尝试清空弹窗
21-Feb-24 01:18:09 - INFO - ocr结果2
21-Feb-24 01:18:09 - INFO - 当前聚焦队伍B
21-Feb-24 01:18:09 - INFO - 执行step:4 action:1 队伍B->move right
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
21-Feb-24 01:18:11 - INFO - 三角识别失败，尝试使用砖块识别
输入的图片全黑，没有有效像素点
21-Feb-24 01:18:11 - INFO - 点击[730, 287]
21-Feb-24 01:18:12 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:18:12 - INFO - 尝试呼出弹窗
21-Feb-24 01:18:14 - INFO - 尝试清空弹窗
21-Feb-24 01:18:17 - INFO - PHASE结束
21-Feb-24 01:18:21 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:18:22 - INFO - 尝试呼出弹窗
21-Feb-24 01:18:26 - INFO - 尝试清空弹窗
21-Feb-24 01:18:29 - INFO - ocr结果1
21-Feb-24 01:18:29 - INFO - 当前聚焦队伍A
21-Feb-24 01:18:29 - INFO - 执行step:5 action:0 队伍A->move right
21-Feb-24 01:18:31 - INFO - 点击[647, 466]
21-Feb-24 01:18:32 - INFO - 等待阶段，是否可能会进入局内战斗：False
21-Feb-24 01:18:32 - INFO - 尝试呼出弹窗
21-Feb-24 01:18:34 - INFO - 尝试清空弹窗
21-Feb-24 01:18:37 - INFO - ocr结果1
21-Feb-24 01:18:38 - INFO - ocr结果2
21-Feb-24 01:18:38 - INFO - 当前聚焦队伍B
21-Feb-24 01:18:38 - INFO - 执行step:5 action:1 队伍B->move right-up
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
输入的图片全黑，没有有效像素点
21-Feb-24 01:18:40 - INFO - 三角识别失败，尝试使用砖块识别
21-Feb-24 01:18:40 - INFO - 点击[681, 211]
21-Feb-24 01:18:41 - INFO - 等待阶段，是否可能会进入局内战斗：True
21-Feb-24 01:18:47 - INFO - 有开关弹窗效果
21-Feb-24 01:18:47 - INFO - PHASE结束
21-Feb-24 01:18:52 - INFO - 等待阶段，是否可能会进入局内战斗：True
21-Feb-24 01:19:01 - INFO - 有开关弹窗效果
21-Feb-24 01:19:01 - INFO - 24-4.json执行完毕
21-Feb-24 01:19:01 - INFO - 判断任务GridQuest执行结果是否可控
21-Feb-24 01:19:21 - WARNING - run_until exceeded max times
21-Feb-24 01:19:21 - WARNING - 任务GridQuest执行后条件不成立或超时
21-Feb-24 01:19:21 - INFO - 尝试返回主页
21-Feb-24 01:19:22 - WARNING - Cannot find the target pattern ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png when try to click
21-Feb-24 01:19:25 - WARNING - Cannot find the target pattern ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png when try to click
21-Feb-24 01:19:29 - WARNING - Cannot find the target pattern ./DATA/assets_jp/BUTTON/BUTTON_HOME_ICON.png when try to click

程序运行结束，如有问题请加群(441069156)反馈，在Github上检查下是否有版本更新
https://github.com/sanmusen214/BAAH
按回车键继续:21-Feb-24 01:19:32 - WARNING - run_until exceeded max times
21-Feb-24 01:19:32 - ERROR - 返回主页失败
Traceback (most recent call last):
  File "C:\Users\liu55\PycharmProjects\BAAH\main.py", line 54, in <module>
    BAAH_main()
  File "C:\Users\liu55\PycharmProjects\BAAH\BAAH.py", line 156, in BAAH_main
    my_AllTask.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\myAllTask.py", line 70, in run
    task.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\InQuest.py", line 52, in on_run
    PushQuest("normal", push_normal_ind, level_ind=config.userconfigdict["PUSH_NORMAL_QUEST_LEVEL"]-1).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 54, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\PushQuest.py", line 156, in on_run
    GridQuest(grider=grider, backtopic=lambda: match(page_pic(PageName.PAGE_QUEST_SEL)), require_type=require_types[self.require_type_ind]).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 61, in run
    raise Exception("任务{}执行后条件不成立或超时，且无法正确返回主页，程序退出".format(self.name))
Exception: 任务GridQuest执行后条件不成立或超时，且无法正确返回主页，程序退出

**Comment by sanmusen214** [comment]
有空看下1.3.4还有没有该问题

**Comment by ly5519** [comment]
目前最新commit测试

手工队无法配置B队，彩虹队卡住，和之前情况一样

**Comment by ly5519** [comment]
截至目前 commit 97e5895 24-4通关成功
