### ISSUE TITLE
gui程序的8000端口被占用，希望能自定义

### ISSUE THREAD

**Issue by nange183** [sanmusen214/BAAH#28]
如题

**Comment by sanmusen214** [comment]
GUI使用的native.find_open_port()寻找8000端口及之后的可用端口运行。我这边测试的8000端口被占用的情况下是可以自动使用8001打开的。
![image](https://github.com/sanmusen214/BAAH/assets/61451492/794ddd08-a04f-40ec-b606-2bbde3692c05)

建议你再检查下你是不是已经打开了GUI的命令行。
