### ISSUE TITLE
普通图24-5通关失败

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#30]
15-Mar-24 01:11:06 - WARNING - 缺少PORT_IS_USED配置，使用默认值False
15-Mar-24 01:11:06 - WARNING - 缺少EMULATOR_PROCESS_PID配置，使用默认值None
15-Mar-24 01:11:06 - WARNING - 缺少GUI_OPEN_IN_WEB配置，使用默认值True
15-Mar-24 01:11:06 - WARNING - 缺少LAST_TEAM_SET配置，使用默认值[]
15-Mar-24 01:11:06 - WARNING - 缺少CAFE_HAD_INVITED配置，使用默认值True
15-Mar-24 01:11:06 - INFO - 读取指定的config文件: push.json
15-Mar-24 01:11:06 - WARNING - 缺少PORT_IS_USED配置，使用默认值False
15-Mar-24 01:11:06 - WARNING - 缺少EMULATOR_PROCESS_PID配置，使用默认值None
15-Mar-24 01:11:06 - WARNING - 缺少GUI_OPEN_IN_WEB配置，使用默认值True
15-Mar-24 01:11:06 - WARNING - 缺少LAST_TEAM_SET配置，使用默认值[]
15-Mar-24 01:11:06 - WARNING - 缺少CAFE_HAD_INVITED配置，使用默认值True
15-Mar-24 01:11:07 - INFO - 读取的config文件: push.json
15-Mar-24 01:11:07 - INFO - 模拟器:
15-Mar-24 01:11:07 - INFO - 端口:16384
15-Mar-24 01:11:07 - INFO - 区服:JP
15-Mar-24 01:11:07 - INFO - 未配置模拟器路径，跳过启动模拟器
+======================================BAAH====================================== +
||                                 Version: 1.3.6                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                                 QQ群: 441069156                                 ||
||                                                                                ||
+================================================================================+
15-Mar-24 01:11:08 - INFO - 删除ca51ec59.png
15-Mar-24 01:11:10 - INFO - 截图文件大小为525KB
15-Mar-24 01:11:10 - INFO - adb与模拟器连接正常
15-Mar-24 01:11:10 - INFO - 图片分辨率为1280*720
15-Mar-24 01:11:10 - INFO - adb连接成功
15-Mar-24 01:11:10 - INFO - 跳过启动加速器
15-Mar-24 01:11:10 - INFO - 当前运行的app是：com.YostarJP.BlueArchive/com.yostarjp.bluearchive.MxUnityPlayerActivity
15-Mar-24 01:11:10 - INFO - 检测到游戏已经在运行
15-Mar-24 01:11:10 - INFO - 运行任务
15-Mar-24 01:11:10 - INFO - 判断任务EnterGame是否可以执行
15-Mar-24 01:11:10 - INFO - 尝试返回主页
15-Mar-24 01:11:14 - INFO - 返回主页成功
15-Mar-24 01:11:19 - WARNING - run_until exceeded max times
15-Mar-24 01:11:19 - WARNING - 任务EnterGame执行前条件不成立或超时，跳过此任务
15-Mar-24 01:11:19 - INFO - 判断任务InQuest是否可以执行
15-Mar-24 01:11:19 - INFO - 执行任务InQuest
15-Mar-24 01:11:26 - INFO - 设置了推普通图任务，开始推图
15-Mar-24 01:11:26 - INFO - 判断任务PushQuest是否可以执行
15-Mar-24 01:11:27 - INFO - 执行任务PushQuest
15-Mar-24 01:11:27 - INFO - switch to normal quest
15-Mar-24 01:11:27 - INFO - 尝试跳转至页面 24
15-Mar-24 01:11:33 - INFO - 尝试翻到关卡 5
15-Mar-24 01:11:37 - INFO - 分割后的关卡序号：['24', '5']
15-Mar-24 01:11:37 - INFO - 格子关卡：24-5，开始推图
15-Mar-24 01:11:37 - INFO - 识别到S标签，判断为走格子战斗
15-Mar-24 01:11:39 - INFO - 判断任务GridQuest是否可以执行
配队结束后请直接返回至走格子界面，不用点击出击。输入回车继续：15-Mar-24 01:11:42 - INFO - 执行任务GridQuest
15-Mar-24 01:11:42 - INFO - 成功读取关卡文件24-5.json，开始执行
15-Mar-24 01:11:42 - INFO - 未保存适合的配置，请按照以下队伍要求配队
15-Mar-24 01:11:42 - INFO -     编辑部队-> 1部队: purple 振动 left-up
15-Mar-24 01:11:42 - INFO -     编辑部队-> 2部队: red 爆发 right-down
15-Mar-24 01:11:42 - INFO - 同时，请确保你的SKIP战斗设置为开启，PHASE自动结束为关闭

15-Mar-24 01:11:52 - INFO - 配队信息已更新
15-Mar-24 01:11:52 - INFO - 配置队伍A
15-Mar-24 01:11:54 - INFO - 点击出击
15-Mar-24 01:11:58 - INFO - 配置队伍B
15-Mar-24 01:12:00 - INFO - 点击出击
15-Mar-24 01:12:06 - INFO - 开始战斗！
15-Mar-24 01:12:10 - INFO - 判断是否需要设置自动战斗开启和PHASE自动结束关闭
15-Mar-24 01:12:10 - INFO - ocr结果1
15-Mar-24 01:12:10 - INFO - 当前聚焦队伍A
15-Mar-24 01:12:10 - INFO - 执行step:0 action:0 队伍A->move right
15-Mar-24 01:12:12 - INFO - 点击[630, 304]
15-Mar-24 01:12:13 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:13 - INFO - 尝试呼出弹窗
15-Mar-24 01:12:16 - INFO - 尝试清空弹窗
15-Mar-24 01:12:18 - INFO - ocr结果2
15-Mar-24 01:12:18 - INFO - 当前聚焦队伍B
15-Mar-24 01:12:18 - INFO - 执行step:0 action:1 队伍B->move right
15-Mar-24 01:12:20 - INFO - 点击[753, 473]
15-Mar-24 01:12:21 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:21 - INFO - 尝试呼出弹窗
15-Mar-24 01:12:23 - INFO - 尝试清空弹窗
15-Mar-24 01:12:26 - INFO - PHASE结束
15-Mar-24 01:12:28 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:28 - INFO - 尝试呼出弹窗
15-Mar-24 01:12:39 - INFO - 尝试清空弹窗
15-Mar-24 01:12:41 - INFO - ocr结果1
15-Mar-24 01:12:41 - INFO - 当前聚焦队伍A
15-Mar-24 01:12:41 - INFO - 执行step:1 action:0 队伍A->move right-up
15-Mar-24 01:12:43 - INFO - 点击[822, 368]
15-Mar-24 01:12:44 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:44 - INFO - 尝试呼出弹窗
15-Mar-24 01:12:44 - INFO - 尝试清空弹窗
15-Mar-24 01:12:47 - INFO - ocr结果2
15-Mar-24 01:12:47 - INFO - 当前聚焦队伍B
15-Mar-24 01:12:47 - INFO - 执行step:1 action:1 队伍B->move right
15-Mar-24 01:12:49 - INFO - 点击[839, 485]
15-Mar-24 01:12:50 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:50 - INFO - 尝试呼出弹窗
15-Mar-24 01:12:52 - INFO - 尝试清空弹窗
15-Mar-24 01:12:54 - INFO - PHASE结束
15-Mar-24 01:12:57 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:12:57 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:08 - INFO - 尝试清空弹窗
15-Mar-24 01:13:10 - INFO - ocr结果1
15-Mar-24 01:13:10 - INFO - 当前聚焦队伍A
15-Mar-24 01:13:10 - INFO - 执行step:2 action:0 队伍A->move right
15-Mar-24 01:13:12 - INFO - 点击[835, 382]
15-Mar-24 01:13:13 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:13 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:19 - INFO - 尝试清空弹窗
15-Mar-24 01:13:22 - INFO - ocr结果2
15-Mar-24 01:13:22 - INFO - 当前聚焦队伍B
15-Mar-24 01:13:22 - INFO - 执行step:2 action:1 队伍B->move right-up
15-Mar-24 01:13:24 - INFO - 点击[781, 405]
15-Mar-24 01:13:25 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:25 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:25 - INFO - 尝试清空弹窗
15-Mar-24 01:13:27 - INFO - PHASE结束
15-Mar-24 01:13:30 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:30 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:34 - INFO - 尝试清空弹窗
15-Mar-24 01:13:37 - INFO - ocr结果1
15-Mar-24 01:13:37 - INFO - 当前聚焦队伍A
15-Mar-24 01:13:37 - INFO - 执行step:3 action:0 队伍A->portal left
15-Mar-24 01:13:38 - INFO - 点击[633, 366]
15-Mar-24 01:13:42 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:42 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:44 - INFO - 尝试清空弹窗
15-Mar-24 01:13:46 - INFO - ocr结果2
15-Mar-24 01:13:46 - INFO - 当前聚焦队伍B
15-Mar-24 01:13:46 - INFO - 执行step:3 action:1 队伍B->move right-up
15-Mar-24 01:13:48 - INFO - 点击[814, 382]
15-Mar-24 01:13:49 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:49 - INFO - 尝试呼出弹窗
15-Mar-24 01:13:54 - INFO - 尝试清空弹窗
15-Mar-24 01:13:56 - INFO - PHASE结束
15-Mar-24 01:13:58 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:13:58 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:03 - INFO - 尝试清空弹窗
15-Mar-24 01:14:05 - INFO - ocr结果1
15-Mar-24 01:14:06 - INFO - ocr结果2
15-Mar-24 01:14:06 - INFO - 当前聚焦队伍B
15-Mar-24 01:14:06 - INFO - 执行step:4 action:0 队伍B->move left-down
15-Mar-24 01:14:08 - INFO - 点击[723, 461]
15-Mar-24 01:14:09 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:14:09 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:10 - INFO - 尝试清空弹窗
15-Mar-24 01:14:12 - INFO - ocr结果1
15-Mar-24 01:14:12 - INFO - 当前聚焦队伍A
15-Mar-24 01:14:12 - INFO - 执行step:4 action:1 队伍A->exchange right-up
15-Mar-24 01:14:14 - INFO - 点击[584, 241]
15-Mar-24 01:14:17 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:14:17 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:20 - INFO - 尝试清空弹窗
15-Mar-24 01:14:22 - INFO - ocr结果1
15-Mar-24 01:14:22 - INFO - 当前聚焦队伍A
15-Mar-24 01:14:22 - INFO - 执行step:4 action:2 队伍A->portal center
15-Mar-24 01:14:24 - INFO - 点击[524, 317]
15-Mar-24 01:14:29 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:14:29 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:31 - INFO - 尝试清空弹窗
15-Mar-24 01:14:34 - INFO - ocr结果1
15-Mar-24 01:14:34 - INFO - 当前聚焦队伍A
15-Mar-24 01:14:34 - INFO - 执行step:4 action:3 队伍A->move left-down
15-Mar-24 01:14:36 - INFO - 点击[611, 536]
15-Mar-24 01:14:37 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:14:37 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:39 - INFO - 尝试清空弹窗
15-Mar-24 01:14:41 - INFO - PHASE结束
15-Mar-24 01:14:44 - INFO - 等待阶段，是否可能会进入局内战斗：False
15-Mar-24 01:14:44 - INFO - 尝试呼出弹窗
15-Mar-24 01:14:46 - INFO - 尝试清空弹窗
15-Mar-24 01:14:49 - INFO - ocr结果1
15-Mar-24 01:14:49 - INFO - 当前聚焦队伍A
15-Mar-24 01:14:49 - INFO - 执行step:5 action:0 队伍A->move left-down
15-Mar-24 01:14:50 - INFO - 点击[555, 586]
15-Mar-24 01:14:51 - INFO - 等待阶段，是否可能会进入局内战斗：True
15-Mar-24 01:14:57 - INFO - 有开关弹窗效果
15-Mar-24 01:14:57 - INFO - PHASE结束
15-Mar-24 01:15:02 - INFO - 等待阶段，是否可能会进入局内战斗：True
15-Mar-24 01:15:07 - INFO - 有开关弹窗效果
15-Mar-24 01:15:07 - INFO - 24-5.json执行完毕
15-Mar-24 01:15:07 - INFO - 判断任务GridQuest执行结果是否可控
15-Mar-24 01:15:27 - WARNING - run_until exceeded max times
15-Mar-24 01:15:27 - WARNING - 任务GridQuest执行后条件不成立或超时
15-Mar-24 01:15:27 - INFO - 尝试返回主页
15-Mar-24 01:15:31 - ERROR - 返回主页失败
Traceback (most recent call last):
  File "C:\Users\liu55\PycharmProjects\BAAH\main.py", line 55, in <module>
    BAAH_main()
  File "C:\Users\liu55\PycharmProjects\BAAH\BAAH.py", line 187, in BAAH_main
    my_AllTask.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\myAllTask.py", line 70, in run
    task.run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 57, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\InQuest.py", line 49, in on_run
    PushQuest("normal", push_normal_ind, level_ind=config.userconfigdict["PUSH_NORMAL_QUEST_LEVEL"]-1).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 57, in run
    self.on_run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\InQuest\PushQuest.py", line 156, in on_run
    GridQuest(grider=grider, backtopic=lambda: match(page_pic(PageName.PAGE_QUEST_SEL)), require_type=require_types[self.require_type_ind]).run()
  File "C:\Users\liu55\PycharmProjects\BAAH\modules\AllTask\Task.py", line 64, in run
    raise Exception("任务{}执行后条件不成立或超时，且无法正确返回主页，程序退出".format(self.name))
Exception: 任务GridQuest执行后条件不成立或超时，且无法正确返回主页，程序退出
+======================================BAAH====================================== +
||                                 Version: 1.3.6                                 ||
||                  Bilibili: https://space.bilibili.com/7331920                  ||
||                  Github: https://github.com/sanmusen214/BAAH                   ||
||                                 QQ群: 441069156                                 ||
||                                                                                ||
+================================================================================+

程序运行结束，如有问题请加群(441069156)反馈，在Github上检查下是否有版本更新
https://github.com/sanmusen214/BAAH
出现错误，按回车键退出:

**Comment by ly5519** [comment]
视频已上传群文件

**Comment by sanmusen214** [comment]
现在出场位置识别失败会提示人为干预修正，虽然感觉不如等待日服简易攻略普及其他服（
