### ISSUE TITLE
关于BAAH的公网安全性问题

### ISSUE THREAD

**Issue by citrusreticulata** [sanmusen214/BAAH#31]
我发现BAAH换用了新UI之后会使用浏览器打开网页前端。
而绑定前端访问的ip地址时，应该是使用了任意host(0.0.0.0)，这导致了安全隐患。
如果所用的电脑为公网ip，则BAAH会向公网暴露该服务，其他主机不需要认证就可以打开你电脑上的BAAH。

建议添加配置项，例如：
- 可以选择是否只在`127.0.0.1`开启服务，禁掉非局域网ip
- 可以手动选定绑定的ip

或者干脆只向本地`127.0.0.1`开启服务

**Comment by sanmusen214** [comment]
感谢反馈，已于 66aed72 修复
