### ISSUE TITLE
An idea for TimeTable

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#33]
最近自动挂着挂着突然发现还可以有7张票（原来只有6张票的）
后面就把自动挂的停了，现在基本每天手动点   ~~准备上7费~~
就在想我自己的逻辑条件是：
1. 不点没有满区域的地方
2. 点好感度多的地方
3. 尽量点等级高的，出材料也更贵点

就在想做一个类似于权重控制
最后遍历每个学院的每个小地区，把所有的权重相加，取前几个进行炸票
![image](https://github.com/sanmusen214/BAAH/assets/77131638/8183c712-fab1-4967-89d7-464d6f34d8ff)

趁着有这个想法，刚看了看openCV，趁着还有一股子冲劲还没消失，看森哥有无这方面的意图，愿意的话我就花时间在这上面开发一下

**Comment by sanmusen214** [comment]
ok哇，靠match_pixel应该可以，注意适配多服

**Comment by sanmusen214** [comment]
还在弄吗

**Comment by ly5519** [comment]
这段时间工作有点忙，搁置了一下，明天给你交个初版，😂sry my bad

**Comment by ly5519** [comment]
打完大决战就开始写
![image](https://github.com/sanmusen214/BAAH/assets/77131638/699f8943-df32-4d04-92ce-2352988bc40e)

**Comment by sanmusen214** [comment]
> 这段时间工作有点忙，搁置了一下，明天给你交个初版，😂sry my bad

没事我就随口问问，最近我也没怎么捣鼓

**Comment by ly5519** [comment]
https://github.com/sanmusen214/BAAH/blob/5176d81486d9e7dc85fd66a303b12a8734e8288e/modules/AllTask/InTimeTable/SmartSelect.py#L80

森哥有个问题噢这里学校学生不够，学校没开，点击箭头是不是直接跳过了那个没开的学校，然后idx又是连着的，当时我就是解决这个问题头疼，就想着做文字识别钉死每个学校名叫啥它下标是啥

**Comment by sanmusen214** [comment]
> 学校没开，点击箭头是不是直接跳过了那个没开的学校，然后idx又是连着的

是的，比较重要的就是根据右上角区域判断是否回到第一个学校
