### ISSUE TITLE
剧情强制失败无法正常识别

### ISSUE THREAD

**Issue by Rudfio** [sanmusen214/BAAH#38]
主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。
![1](https://github.com/sanmusen214/BAAH/assets/125795701/34e3d342-d42a-4316-b35e-ca2e7f738a3b)

**Comment by sanmusen214** [comment]
> 主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。 ![1](https://private-user-images.githubusercontent.com/125795701/337348636-34e3d342-d42a-4316-b35e-ca2e7f738a3b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTI2NjMsIm5iZiI6MTcxNzcxMjM2MywicGF0aCI6Ii8xMjU3OTU3MDEvMzM3MzQ4NjM2LTM0ZTNkMzQyLWQ0MmEtNDMxNi1iMzVlLWNhMmU3ZjczOGEzYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiMzA3Yzg2NzY1YzZjMjBkNzEzMTc2YjZjYzc1MDhmNjg4MDE0OGE4OGQ5MGEwNWIwMjg4MjZhOWQxNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GKU0kMB7mlnGI4-uhlLTvGcCHSRHMXKR3Gd1PjNnsY)

这是哪一关

**Comment by Rudfio** [comment]
> > 主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。 ![1](https://private-user-images.githubusercontent.com/125795701/337348636-34e3d342-d42a-4316-b35e-ca2e7f738a3b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTI2NjMsIm5iZiI6MTcxNzcxMjM2MywicGF0aCI6Ii8xMjU3OTU3MDEvMzM3MzQ4NjM2LTM0ZTNkMzQyLWQ0MmEtNDMxNi1iMzVlLWNhMmU3ZjczOGEzYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiMzA3Yzg2NzY1YzZjMjBkNzEzMTc2YjZjYzc1MDhmNjg4MDE0OGE4OGQ5MGEwNWIwMjg4MjZhOWQxNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GKU0kMB7mlnGI4-uhlLTvGcCHSRHMXKR3Gd1PjNnsY)
> 
> 这是哪一关

> > 主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。 ![1](https://private-user-images.githubusercontent.com/125795701/337348636-34e3d342-d42a-4316-b35e-ca2e7f738a3b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTI2NjMsIm5iZiI6MTcxNzcxMjM2MywicGF0aCI6Ii8xMjU3OTU3MDEvMzM3MzQ4NjM2LTM0ZTNkMzQyLWQ0MmEtNDMxNi1iMzVlLWNhMmU3ZjczOGEzYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiMzA3Yzg2NzY1YzZjMjBkNzEzMTc2YjZjYzc1MDhmNjg4MDE0OGE4OGQ5MGEwNWIwMjg4MjZhOWQxNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GKU0kMB7mlnGI4-uhlLTvGcCHSRHMXKR3Gd1PjNnsY)
> 
> 这是哪一关

主线剧情5百花缭乱篇，第一章第18关，另外还有同章里第12关、第9关都是强制失败的关，全都无法正常识别

**Comment by sanmusen214** [comment]
> > > 主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。 ![1](https://private-user-images.githubusercontent.com/125795701/337348636-34e3d342-d42a-4316-b35e-ca2e7f738a3b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTI2NjMsIm5iZiI6MTcxNzcxMjM2MywicGF0aCI6Ii8xMjU3OTU3MDEvMzM3MzQ4NjM2LTM0ZTNkMzQyLWQ0MmEtNDMxNi1iMzVlLWNhMmU3ZjczOGEzYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiMzA3Yzg2NzY1YzZjMjBkNzEzMTc2YjZjYzc1MDhmNjg4MDE0OGE4OGQ5MGEwNWIwMjg4MjZhOWQxNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GKU0kMB7mlnGI4-uhlLTvGcCHSRHMXKR3Gd1PjNnsY)
> > 
> > 
> > 这是哪一关
> 
> > > 主线剧情强制失败的关，显示“执行条件不成立或超时，且无法正确返回主页”，建议添加一个当剧情战斗失败后自动点击确定的功能。 ![1](https://private-user-images.githubusercontent.com/125795701/337348636-34e3d342-d42a-4316-b35e-ca2e7f738a3b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTI2NjMsIm5iZiI6MTcxNzcxMjM2MywicGF0aCI6Ii8xMjU3OTU3MDEvMzM3MzQ4NjM2LTM0ZTNkMzQyLWQ0MmEtNDMxNi1iMzVlLWNhMmU3ZjczOGEzYi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMjE5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjhiMzA3Yzg2NzY1YzZjMjBkNzEzMTc2YjZjYzc1MDhmNjg4MDE0OGE4OGQ5MGEwNWIwMjg4MjZhOWQxNjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GKU0kMB7mlnGI4-uhlLTvGcCHSRHMXKR3Gd1PjNnsY)
> > 
> > 
> > 这是哪一关
> 
> 主线剧情5百花缭乱篇，第一章第18关，另外还有同章里第12关、第9关都是强制失败的关，全都无法正常识别

好的感谢反馈，这几天修下

**Comment by sanmusen214** [comment]
于开发分支修复
