### ISSUE TITLE
Hardstage is not running properly

### ISSUE THREAD

**Issue by boltth696** [sanmusen214/BAAH#42]
for some reason when the program starts doing hard stages it goes inside mission but does not start hard stage

**Comment by sanmusen214** [comment]
Can you attach the screenshot of the terminal

**Comment by boltth696** [comment]
![34](https://github.com/sanmusen214/BAAH/assets/160701607/483966c4-7c10-46c6-8646-28c6cfd580dd)

**Comment by sanmusen214** [comment]
Well the character set can not display Chinese right. I will add i18n in the terminal later.

For the issue, by looking the length of the sentence. it seems that it uses too many attempts to start the HardQuest task. 

1. Please make sure the pic data in the folder "BAAH/BAAH1.4.6/DATA/assets_global_en/PAGE/PAGE_QUEST_SEL.png is as this:
![PAGE_QUEST_SEL](https://github.com/sanmusen214/BAAH/assets/61451492/fab0e93a-35ad-471c-9b32-2a1ca3015947), which is also same with the left-up title of the hard stage. If not, please download the newest update pack and decompress it (especially the Data folder).
2. Please make sure the config of the hard stage is set properly, 
![image](https://github.com/sanmusen214/BAAH/assets/61451492/912c0325-8ef1-4cb2-b40e-4d0e7a6784b9)

**Comment by boltth696** [comment]
Thanks, doing the first method help fixed the problem

**Comment by sanmusen214** [comment]
Great
