### ISSUE TITLE
普通商店购买失败

### ISSUE THREAD

**Issue by JG1214** [sanmusen214/BAAH#44]
![91f213fa-6f9d-4bea-a71c-e03636a05287](https://github.com/sanmusen214/BAAH/assets/166608224/e293889c-9a6b-4a89-a20f-949625b2a28d)
![f2110571-19d9-4b42-af0e-1a8fcafa3d6d](https://github.com/sanmusen214/BAAH/assets/166608224/624ecccb-7301-4866-9382-600bbfc86d66)

**Comment by ly5519** [comment]
![image](https://github.com/sanmusen214/BAAH/assets/77131638/959e5999-9b87-470f-a05c-2d3d4cbf0984)

**Comment by ly5519** [comment]
这边横着竖着购买日服是没啥问题的，您能提供更详细的视频或者日志吗

**Comment by JG1214** [comment]
> 这边横着竖着购买日服是没啥问题的，您能提供更详细的视频或者日志吗
已解决，我每列都设置1所以没成功，改了234后就可以了sry
