### ISSUE TITLE
在使用脚本的过程中，开了uu加速器脚本就自动停止了

### ISSUE THREAD

**Issue by HDZM** [sanmusen214/BAAH#55]
不知道是什么原因

**Comment by sanmusen214** [comment]
能否提供脚本运行时的日志截图和模拟器的页面截图

> 不知道是什么原因

**Comment by sanmusen214** [comment]
> 不知道是什么原因

建议使用模拟器里的UU加速器。如果你使用的是电脑上的UU确实会有问题，详见 https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/5528#issuecomment-1641539777
