### ISSUE TITLE
增加活动中图标识别

### ISSUE THREAD

**Issue by LLL1997** [sanmusen214/BAAH#56]
需求:  识别普通关卡中左上侧的活动中图标，来决定是否执行该任务，并在gui中增加开关来判断是否执行该逻辑流程

关联特殊委托，学院，困难关卡

增加功能的必要性&好处 : 这些关卡没有多倍活动刷取效率低，如果追求高效率，需要经常调整，增加识别能优化使用体验，使用起来更加灵活

实现 : 限定位置来识图活动中图标，在特殊任务中，粉头发干扰识别比较严重，所以得限定位置来识图。目前暂时想到的是这种方法

**Comment by sanmusen214** [comment]
ok，但是问题是这个功能必须得有双倍活动才能做起来（，然后如果有多服务器的兼容的话最好写在一起

**Comment by sanmusen214** [comment]
可能用固定位置像素的颜色识别好一点，分辨率低了的情况下位置上的移动会改变字体的渲染，模板匹配准确率不是那么高。
固定位置的像素颜色匹配可以看看这个（modules/AllTask/InMomotalk/InMomotalk.py）里面的whether_has_red_icon方法

**Comment by LLL1997** [comment]
ok,这个可能要一段时间写和测试（

**Comment by LLL1997** [comment]
整完了，现在国际服的特殊任务识别和逻辑是没问题的。还有日服的quest的判断也没问题了，其他待测。
目前活动少，我测完没问题再提交

**Comment by sanmusen214** [comment]
Closed with https://github.com/sanmusen214/BAAH/releases/tag/BAAH1.6.2
