### ISSUE TITLE
优化商店使用

### ISSUE THREAD

**Issue by LLL1997** [sanmusen214/BAAH#57]
1.战术商店增加整个功能的独立开关，而普通商店不是共用一个整个功能开关，这样更灵活一点

2.普通商店点击增加按钮出来的文本框更改为自增，比如第一下按是1，第二下是2，以此类推。
目前的新增加出来的文本框都是 1

3，(不重要,可能意义不大)
可以给某个购买文本框增加个小开关，当然这样会造成界面不美观，也许会造成页面不美观，元素过多，不简洁

**Comment by sanmusen214** [comment]
1. ok, 就是给两个商店各自加功能开关
2. ok，改 gui/components/list_edit_area.py 里面 add_item_item逻辑应该就行了
3. ok，参考 ec07ca4 ，调用list_edit_area的时候传（has_switch=True) 就会给列表单个项目最后额外加一个True/False值

**Comment by LLL1997** [comment]
整完了 森哥有空审查下代码
https://github.com/sanmusen214/BAAH/pull/58

**Comment by sanmusen214** [comment]
合到dev了
