### ISSUE TITLE
国际服最近一次维护后，咖啡厅相关功能失效

### ISSUE THREAD

**Issue by zhangfangte** [sanmusen214/BAAH#60]
国际服最近一次维护后，咖啡厅内的UI做了微调，最明显的就是左上角“夏萊附設咖啡廳”文字变成了“咖啡廳”。并且咖啡厅相关插件功能失效。DATA/assets/PAGE/PAGE_CAFE.png这个文件或许也需要更新一下？
![MuMu12-20240710-173918](https://github.com/sanmusen214/BAAH/assets/90367622/8ae915b1-d9e0-46a0-b246-0ebf5430e5f2)

**Comment by sanmusen214** [comment]
已修复捏

**Comment by zhangfangte** [comment]
感谢光速对应！！辛苦了！！
