### ISSUE TITLE
增加游戏自动更新功能

### ISSUE THREAD

**Issue by LLL1997** [sanmusen214/BAAH#67]
大概是用第三方软件，比如qoo，taptap之类的来配合实现，通过ocr和识图配合来判断是否需要更新游戏，实现类似开启vpn功能，可添加步骤的一系列动作

**Comment by sanmusen214** [comment]
那其实这个用VPN那块的功能就可以代替。要搞自动更新的话不如想办法从cdn拉下来包adb安装

**Comment by LLL1997** [comment]
> 那其实这个用VPN那块的功能就可以代替。要搞自动更新的话不如想办法从cdn拉下来包adb安装

从cdn拉下来维护成本太大了吧，有3个服，4个不同的包，不如直接从应用市场更新可能好点？
更新功能做成独立的会不会好点，现有的vpn功能的问题是没有检测游戏中更新弹窗的问题，要用vpn那块来实现更新游戏估计得定时检查或者每次都检查

**Comment by sanmusen214** [comment]
> 从cdn拉下来维护成本太大了吧，有3个服，4个不同的包，不如直接从应用市场更新可能好点？ 

不知道能不能找到下apk的url，自己去维护个cdn不大可能。如果能搞到靠谱的下载源的话，用adb检测下本地包体号和下载站的包体号就可以在启动游戏前就检测更新了。

> 更新功能做成独立的会不会好点，现有的vpn功能的问题是没有检测游戏中更新弹窗的问题，要用vpn那块来实现更新游戏估计得定时检查或者每次都检查

这样看是可以的，但是还是建议先看看有没有什么第三方网站可以提供最新的包体号和下载包

**Comment by sanmusen214** [comment]
这个对于用户而言性价比是不是太低了。开加速器操作是国内玩家每次开游戏前必须要弄的，而换包更新每几个月才有一次。会有很多人靠脚本更新游戏吗

**Comment by sanmusen214** [comment]
要不游戏内检测到要下新安装包就直接退出然后邮件通知

**Comment by LLL1997** [comment]
确实有点作用不大，而且不太好写，国际服和日服还好，谷歌商店下载站很多，更新也及时，url也是固定的。
而b服和官服这种下载站点少，可能都要靠app来更新，app得抓包看看链接才知道会不会变动。
总结：性价比确实不高，下载站存在更改url等，额外增加了维护成本

**Comment by LLL1997** [comment]
要不做个检测到更新弹窗，然后可选 
1.直接退出发邮件 
2.执行外部脚本等待结束再继续执行baah 
3.执行类似vpn模块的用户自定义的一系列图像识别动作
这样行吗

**Comment by LLL1997** [comment]
此功能作用不大，且已经找到替代方案：

1.使用自动动化工具进行更新，比如自动任务AutoTask（包名top.xjunz.tasker）进行定时或进入更新页面时，进行进入谷歌或者b站等平台进行更新
2.编写脚本adb定时（app更新时间基本固定）点击谷歌商店的全部更新
3.使用加速功能点击更新

故此功能更新搁置，没有必要增加而造成程序维护难度上升。
