### ISSUE TITLE
希望添加多平台支持

### ISSUE THREAD

**Issue by lonzzi** [sanmusen214/BAAH#69]
目前脚本只适配了 Windows 端，想着把脚本部署到服务器（Ubuntu 环境）上配合 redroid 每天自动运行。

**Comment by sanmusen214** [comment]
> 想着把脚本部署到服务器（Ubuntu 环境）上配合 redroid 每天自动运行。

尝试一下按照 [文档](https://github.com/sanmusen214/BAAH/blob/main/docs/README_cn.md) 里的python执行源码的方式运行

**Comment by lonzzi** [comment]
> > 想着把脚本部署到服务器（Ubuntu 环境）上配合 redroid 每天自动运行。
> 
> 尝试一下按照 [文档](https://github.com/sanmusen214/BAAH/blob/main/docs/README_cn.md) 里的python执行源码的方式运行

使用源码能跑起来了，不过 adb 截图后图片的处理似乎有点问题，执行了 convert_img 之后会导致本来由 adb 截到的正常的图片无法被读取。

**Comment by lonzzi** [comment]
> > adb 截图后图片的处理似乎有点问题，执行了 convert_img 之后会导致本来由 adb 截到的正常的图片无法被读取。
> 
> convert_img是一些字符转换操作来着，可能只有win端需要转换？如果确定某个平台不需要执行此操作的话可以考虑写个分支判断，还请确认一下Ubuntu环境确实不需要此操作，可以的话请PR(●'◡'●)
> 
> > 以及希望能够在 web 端直接启动脚本并且能够有一个预览的截图（几分钟截图一次并上传至 web 端查看）
> 
> web页面内直接启动已经有了，我不太了解看预览截图的目的是什么，如果是为了查看模拟器内状态的话应该有更好的方案，如果是为了看脚本是否正确执行的话看日志就可以了。
> 
> > 也希望能够在 web 端直接设置定时任务
> 
> BAAH的设计初衷不是常驻后台而是即用即结束，所以目前没有在脚本内置定时任务的计划，你如果在Ubuntu环境需要的话可以用python的第三方库定时执行（比如[schedule](https://schedule.readthedocs.io/en/stable/)) 或者 看看有没有和计划任务程序一样的系统调度机制。

好的，有时间我测试一下多平台下截图的问题，会尽快提 pr ，感谢解答。

**Comment by sanmusen214** [comment]
#71
