### ISSUE TITLE
國際服的競技場功能 按下的位置偏移

### ISSUE THREAD

**Issue by hsd325** [sanmusen214/BAAH#75]
如題
已檢查過模擬器為1280*720 240DPI，BAAH也為最新版

因為不知道出錯的文件儲存位置，所以先給圖片講哪裡出錯
按下位置為圖中紅圈圈起來的位置
![螢幕擷取畫面 2024-07-23 221800](https://github.com/user-attachments/assets/49997e83-3ffe-4650-92b2-3ca657dac654)
![螢幕擷取畫面 2024-07-23 221828](https://github.com/user-attachments/assets/0c9e08bd-2781-4039-b21d-2817b3300d9f)

**Comment by sanmusen214** [comment]
今天公司事情好多😭晚点看看

**Comment by sanmusen214** [comment]
1.4.3修复

**Comment by hsd325** [comment]
好的，感謝您
