### ISSUE TITLE
[BUG]设置活动关卡天数轮回，并没有按照轮回刷而是每天在刷第一天的关卡

### ISSUE THREAD

**Issue by ly5519** [sanmusen214/BAAH#84]
Before you raise this issue, make sure it is not duplicated / 在你提出该issue之前，请确保它从未出现过.

**Describe the bug / 简要描述bug**
设置了活动关卡三天三种材料轮着刷，但是每次只刷第一天的，第一个商店都快搬空了

**Screenshots / 截图**
![image](https://github.com/user-attachments/assets/37182a54-b5d5-4b4c-b671-467485d12f3c)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 日服
 - BAAH version / commit id 4d12b17ebed6646166e4179f68eac124ee12ad7f version 1.5.2

**Comment by sanmusen214** [comment]
没法复现...我这能正常按周期轮到第11关，你以前有这问题吗

![image](https://github.com/user-attachments/assets/58366c35-c3a4-4b14-8248-d8179d93e15d)

**Comment by ly5519** [comment]
有没有存本地LOG我私发你一下

**Comment by ly5519** [comment]
我今天还没跑脚本要不看一下？

**Comment by ly5519** [comment]
[JP_everyday.json](https://github.com/user-attachments/files/16402866/JP_everyday.json)

**Comment by ly5519** [comment]
无法复现，问题关闭/(ㄒoㄒ)/~~再遇到再开
