### ISSUE TITLE
[BUG] B服悬赏通缉没法点击到第九关

### ISSUE THREAD

**Issue by Cyan-grey** [sanmusen214/BAAH#86]
Before you raise this issue, plz make sure it is not duplicated / 在你提出该issue之前，请确保它以前从未被提及过.

**Describe the bug / 描述bug**
[ What you want to do and what the script did / 你想要脚本做什么，而它做了什么出乎意料的事 ]
悬赏通缉三个关卡选择第九关，滑到顶部后开始往下滑动页面查找第九关的时候，停止位置偏下，导致进入关卡按钮偏下无法被点击到

**Screenshots / 截图**
[ Plz attach any screenshots of emulator or logs / 请提供相关日志以及模拟器的截图 ]
![Snipaste_2024-07-30_11-22-28](https://github.com/user-attachments/assets/63ddbc77-786d-4bda-9385-d343e472a8ab)
![Snipaste_2024-07-30_10-19-15](https://github.com/user-attachments/assets/d88ac905-5b96-4e92-ab68-94b02bfdaf9c)
![Snipaste_2024-07-30_10-19-51](https://github.com/user-attachments/assets/6009b448-52e1-4c9b-98f7-136efeb5d41f)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: [e.g. Global]
 B服
 - BAAH version / 你的BAAH版本号: [e.g. 1.5.5]
 Blue Archive Aris Helper 1.5.5

**Comment by sanmusen214** [comment]
文档里面有提到过（常见问题6），把配置文件底部滑动距离取消与区服绑定，然后40改成60。
如果没问题的话请关闭issue

**Comment by Cyan-grey** [comment]
感谢解答
