### ISSUE TITLE
使用mumu模拟器，无法正确打开模拟器（难道不是以端口号打开模拟器的吗）

### ISSUE THREAD

**Issue by doxsw** [sanmusen214/BAAH#89]
**Describe the bug / 描述bug**
无法正确的打开对应端口号的模拟器

**Screenshots / 截图**
![image](https://github.com/user-attachments/assets/fbb37268-b23b-4186-8698-282df061f471)
![image](https://github.com/user-attachments/assets/58ebc6cb-67c9-468a-8523-51a682897b55)
![image](https://github.com/user-attachments/assets/602872d1-f82c-40d9-8b8f-aec68fba14b2)

**Please complete the following information / 请填写以下信息**
- BAAH version / 你的BAAH版本号: BAAH1.5.5

**Comment by sanmusen214** [comment]
是根据模拟器路径来打开的模拟器，看样子你使用了mumu多开，路径后面要加参数 -v 1

![image](https://github.com/user-attachments/assets/eefcde71-ce1c-4930-8e6a-9a2d7bd55718)

**Comment by doxsw** [comment]
虽然，但是难道以端口号打开模拟器难道不是更优解吗（

**Comment by doxsw** [comment]
虽然，但是难道以端口号打开模拟器难道不是更优解吗（
