### ISSUE TITLE
日服游戏界面适配问题

### ISSUE THREAD

**Issue by hpQc** [sanmusen214/BAAH#9]
1.日服与国际服战术对抗战按钮位置不一样，导致运行时点击到合同火力演习

![屏幕截图 2023-12-16 131002](https://github.com/sanmusen214/BAAH/assets/89334541/b6f92aec-fcf2-496d-9443-2dfbf4d394bc)

2.日服与国际服的日程表地区数量不一致导致运行时点击到非目标区域
![屏幕截图 2023-12-16 115348](https://github.com/sanmusen214/BAAH/assets/89334541/b56131c4-adbd-4151-8aed-4e40c40289db)
![屏幕截图 2023-12-16 115752](https://github.com/sanmusen214/BAAH/assets/89334541/8d588003-ec6e-4a57-8932-58fae27474f9)
![QQ图片20231216151618](https://github.com/sanmusen214/BAAH/assets/89334541/80742c39-eeaf-476c-afce-14894f27cd22)
![QQ图片20231216151613](https://github.com/sanmusen214/BAAH/assets/89334541/7f118a05-0f0d-46a5-8ea6-e414a8c3171a)

**Comment by sanmusen214** [comment]
已于 862e858 , b488834 修正，感谢反馈

**Comment by sanmusen214** [comment]
问题已修复，并无更多回复，issue关闭
