### ISSUE TITLE
自动auto并没有正常工作

### ISSUE THREAD

**Issue by doxsw** [sanmusen214/BAAH#90]
**Describe the bug / 描述bug**
[ What you want to do and what the script did / 你想要脚本做什么，而它做了什么出乎意料的事 ]
自动auto并没有正常工作，在进入战斗后一段时间后日志先是”run_until exceeded max times“（似乎是报错）输出两次然后执行”自动auto“，在执行”自动auto“的过程中战斗已经结束了（胜利）然后空点了几次判断我为战斗失败。（auto未开启）

在大难度较高的图时，推图时间变长了，”自动auto“执行了，但是当时auto是开启状态，然后一直在点auto键，直到战斗结束。

**Screenshots / 截图**
![image](https://github.com/user-attachments/assets/0d3091a3-5623-4b39-9564-b1ebe5885ffa)
![image](https://github.com/user-attachments/assets/794afc7c-92ad-460c-8365-251fb9cfcec8)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: 国际服
 - BAAH version / 你的BAAH版本号: BAAH1.5.5

**Comment by sanmusen214** [comment]
战斗时上下黑边关 设置了吗

**Comment by doxsw** [comment]
这个故事告诉我们一定要看完教程（
