### ISSUE TITLE
自动更新BAAH

### ISSUE THREAD

**Issue by doxsw** [sanmusen214/BAAH#92]
**Describe the solution you'd like / 你对于实现该功能有何种建议**
在打开软件时，自动检测BAAH是否有新版本，有就自动更新，无就正常运行（使用github多少有概率连不上，如果增加这个功能的话，可以选择，如果一分钟内没有连接github.com，进入程序并提示可能有新版本）
如果做这个功能的话，可以参考“https://github.com/LmeSzinc/StarRailCopilot”

**Comment by sanmusen214** [comment]
这个功能已经在做了，下个版本发布
