### ISSUE TITLE
添加 web 端身份认证

### ISSUE THREAD

**Issue by lonzzi** [sanmusen214/BAAH#97]
**Is your feature request related to a problem? Please describe. / 该功能请求能解决你认为的何种困难？**
为了将服务发布到公网，需要对 web 添加身份认证增加安全性。

**Describe the solution you'd like / 你对于实现该功能有何种建议**
[ A clear and concise description of what you think about the solution. ]

**Additional context / 补充信息**
[ Add any other context or screenshots about the feature request here. ]

PR: #96 

> 
> 1. web 端鉴权代码来自 [examples/authentication/main.py](https://github.com/zauberzeug/nicegui/blob/main/examples/authentication/main.py), 在此基础上使用了 `bcrypt` 库对密码进行了简单的加密处理。
> 2. 现在能够解析 args 进行更多配置了，具体配置项如下：
> 
> | 配置项 | 默认值    | 备注 |
> | ------ | --------- | ---- |
> | host   | 127.0.0.1 | web 端地址 |
> | auth   | False     | 是否开启 web 端鉴权 |
> | username | admin | 用户名称 |
> | password | admin | 用户密码 |

后来想到其实这密码并没有进行存储也就完全没有必要使用 `bcrypt` 进行加密了，可以将这个密码字段直接写死用简单的 `==` 做判断，并且可以通过 `args` 设置登录的用户名与密码。

**Comment by sanmusen214** [comment]
closed with #96, 我琢磨下，总感觉还是有点复杂了

**Comment by lonzzi** [comment]
> closed with #96, 我琢磨下，总感觉还是有点复杂了

其实就是添加了一个鉴权中间件，不过这些特性默认都是关闭的，只有是 web 端并且开启了 auth 才会有登录验证。
