### ISSUE TITLE
课程表没有正常运行

### ISSUE THREAD

**Issue by doxsw** [sanmusen214/BAAH#99]
**Screenshots / 截图**
[ Plz attach any screenshots of emulator or logs / 请提供相关日志以及模拟器的截图 ]
![image](https://github.com/user-attachments/assets/e0c3dbf4-f00c-4270-9b0e-e26e03596442)

**Please complete the following information / 请填写以下信息**
 - BlueArchive Server / 你的游戏服务器: 国际服
 - BAAH version / 你的BAAH版本号: 1.6.0

**Comment by sanmusen214** [comment]
让我看看国际服又改了什么东西🤔

**Comment by sanmusen214** [comment]
感谢反馈，1.6.1版本应该修复了，没问题的话关下issue

**Comment by doxsw** [comment]
感谢大佬维护
